<?php

global $base_url;
//define('GLOBALSIGHT_WSDL_URL', ($base_url . '/' . drupal_get_path('module', 'tmgmt_globalsight') . '/AmbassadorWebService.xml'));
define('GLOBALSIGHT_WSDL_URL', 'file://' . dirname(__FILE__) . '/AmbassadorWebService.xml');

/**
 * Implements hook_cron().
 */
function tmgmt_globalsight_cron() {
  // Skip if disabled.
  if (variable_get('tmgmt_globalsight_download_on_cron', 1) != 1) {
    return;
  }
  tmgmt_globalsight_get_all();
}

/**
 * Implements hook_menu().
 */
function tmgmt_globalsight_menu() {
  $items['admin/tmgmt/gs'] = array(
    'title' => 'TMGMT GlobalSight settings',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tmgmt_globalsight_admin_form'),
    'file' => 'inc/tmgmt_globalsight.admin.inc',
    'access arguments' => array('access administration pages'),
  );

  $items['admin/tmgmt/gs/test'] = array(
    'title' => 'TMGMT GlobalSight test',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'tmgmt_globalsight_test',
    'access arguments' => array('access administration pages'),
  );

  return $items;
}


function tmgmt_globalsight_test() {
  // Initiate Drupal side settings
  $translator = tmgmt_translator_load('gs');
  if ($translator->plugin == 'gs') {
    drupal_set_message('[success] Translator loaded');
  } else {
    return 'error';
  }
  $connector = new TMGMTGlobalSightConnector($translator);
  if ($connector) {
    drupal_set_message('[success] Connector loaded');
  } else {
    return 'error';
  }
  drupal_set_message('Base url: ' . $connector->base_url);
  drupal_set_message('Endpoint: ' . $connector->endpoint);
  drupal_set_message('File profile ID: ' . $connector->file_profile_id);

  //Ping endpoint
  $tB = microtime(true);
  $fP = fSockOpen($connector->endpoint);
  if (!$fP) {
    drupal_set_message('<b>[error] Ping to endpoint using fSockOpen() unsuccessful!</b>');
  } else {
    $tA = microtime(true);
    $time = round((($tA - $tB) * 1000), 0) . " ms";
    drupal_set_message('[success] Ping to endpoint in ' . $time);
  }

  // Try cURL to endpoint
  $ch = curl_init($connector->endpoint);
  curl_setopt($ch, CURLOPT_TIMEOUT, 5);
  curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
  $data = curl_exec($ch);
  $httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
  curl_close($ch);
  if ($httpcode >= 200 && $httpcode < 300) {
    drupal_set_message('[success] cURL to endpoint successful. Server returned: <br><code><pre>' . $data . '</pre></code>');
  } else {
    drupal_set_message('<b>[error] cURL to endpoint using fSockOpen() unsuccessful! HTTP code: ' . $httpcode . '</b>');
  }

  // Try to login
  $access_token = $connector->login();
  dsm($connector->webservice);
  if ($access_token) {
    drupal_set_message('[success] Login successful. Returned access token is:' . $access_token);
  } else {
    drupal_set_message('<b>[error] Login failed. Cannot continue.</b>');
    return $connector->webservice->debug_str;
  }


  // Get list of locales
  $locs = $connector->getLocales();
  if (is_array($locs)) {
    drupal_set_message('Supported source languages: ' . implode(' , ', $locs['source']));
    drupal_set_message('Supported target languages: ' . implode(' , ', $locs['target']));
  } else {
    drupal_set_message('<b>[error] Could not retrieve supported languages.</b>');
  }

  return 'test';
}


function tmgmt_globalsight_update_links($sourceLanguage, $targetLanguage, $string) {
  preg_match_all('#<a\s.*?(?:href=[\'"](.*?)[\'"]).*?>#is', $string, $matches);
  $links = $matches[1];


  $languages = language_list();//tmgmt_available_languages();

  if (!($sourcePrefix = $languages[$sourceLanguage]->prefix) || !($targetPrefix = $languages[$targetLanguage]->prefix)) {
    return false;
  }


  foreach ($links as $link) {
    if (strpos($link, $sourceLanguage) !== FALSE) {
      $linkReplacement = str_replace($sourcePrefix, $targetPrefix, $link);
      $string = str_replace($link, $linkReplacement, $string);
    }
  }
  return $string;
}

/**
 * Implements hook_tmgmt_ui_job_checkout_before_alter().
 * If there are multiple languages per checkout -- try to merge them into one GS job.
 *
 * @param $redirects
 * @param $jobs
 */
function tmgmt_globalsight_tmgmt_ui_job_checkout_before_alter(&$redirects, &$jobs) {

  // I do not want to intervene if there will be a single job.
  if (count($jobs) < 2) {
    return;
  }
  foreach ($jobs as $key => $job) {
    // All jobs but the first one will be "children jobs"
    if ($key > 0) {
      $job->translator = 'gs';
      if ($job->isTranslatable()) {
        // Child job is disabled, so that it won't even show up in the list of jobs to be translated.
        $job->status = 0;
        // Add the job to the list of associated jobs in parent job
        $jobs[0]->settings['associated_jobs'][$job->tjid] = $job->target_language;
        // Flag this job as a child job (cannot be translated individually)
        $job->settings['child_job'] = true;
        $job->label = $job->label . ' (GlobalSight child)';

        $params = array(
          '@url' => '/admin/tmgmt/jobs/' . $jobs[0]->tjid,
          '@tjid' => $jobs[0]->tjid,
        );

        $job->addMessage(t('This job was sent to GlobalSight as part of job <a href="@url">@tjid</a>. It cannot be translated individually.', $params));
      } else {
        // The child job is not translatable.
        $params = array(
          '@url' => '/admin/tmgmt/jobs/' . $job->tjid,
          '@tjid' => $job->tjid,
        );
        $message = t('Job <a href="@url">@tjid</a> is not translatable. It will be skipped.', $params);
        $jobs[0]->addMessage($message);
      }
      $job->save();
    }
  }
  $jobs[0]->save();

  $redirects[] = 'admin/tmgmt/jobs/' . $jobs[0]->tjid;
}

/**
 * Implements hook_form_alter().
 */
function tmgmt_globalsight_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id != 'tmgmt_job_form') {
    return;
  }

  // Make sure there -are- associated jobs before we start tempering with the form
  if (!isset($form_state['tmgmt_job']->settings['associated_jobs']) || count($form_state['tmgmt_job']->settings['associated_jobs']) == 0) {
    return;
  }

  // Load available languages and make nice list of associated jobs
  $available = tmgmt_available_languages();
  $targets = array($available[$form_state['tmgmt_job']->target_language]);
  foreach ($form_state['tmgmt_job']->settings['associated_jobs'] as $language) {
    $targets[] = $available[$language];
  }

  // Language selector will be disabled and hidden because there will be multiple languages
  $form['info']['target_language']['#disabled'] = true;
  $form['info']['target_language']['#title'] = t('Target languages');
  $form['info']['target_language']['#field_prefix'] = '<div class="element-invisible element-hidden">';
  $form['info']['target_language']['#field_suffix'] = '</div>' . implode('<br />', $targets);

  // Set proper title of the page
  drupal_set_title(t('@title (@source to @target)', array(
    '@title' => $form_state['tmgmt_job']->label(),
    '@source' => $available[$form_state['tmgmt_job']->source_language],
    '@target' => implode(', ', $targets),
  )));
}


function tmgmt_globalsight_get_all() {
  // Retrieve the list of all opened jobs
  $result = db_select('tmgmt_globalsight', 't')
    ->fields('t')
    ->condition('status', 0, '>')
    ->execute();

  $links = array();
  // Loop through jobs and check for translations
  while ($record = $result->fetchAssoc()) {
    $job = tmgmt_job_load($record['tjid']);
    if (!$job) {
      continue;
    }
    if (tmgmt_globalsight_ping($job, $record)) {
      $links[] = l('Job ' . $job->tjid . ': ' . $job->label, 'admin/tmgmt/jobs/' . $job->tjid);
    };
  }
  $output = format_plural(count($links), '1 translation job received.', '@count translation jobs received.');
  $output .= theme('item_list', array('items' => $links));

  drupal_set_message($output, 'status');
}


/**
 * Retrieves job data from GS server and, if status is "Exported" or "Localized"
 * recieves translation and adds translated data.
 *
 * @param $job
 *   Loaded TMGMT Job object.
 * @param $record
 *   {tmgmt_globalsight} record connecting TMGMT and GS jobs
 * @return bool
 */
function tmgmt_globalsight_ping($job, $record) {


  $translator = $job->getTranslator();

  // Initialize GlobalSight
  $gs = new TMGMTGlobalSightConnector($translator);

  $status = $gs->getStatus($record['job_name']);

  if ($status === "PERMANENT ERROR") {
    // Update our little mapping table -- archive job
    $record['status'] = 0;
    drupal_write_record('tmgmt_globalsight', $record, array('tjid'));
    $job->aborted('Translation job was cancelled due to unrecoverable error.');
    return false;
  }

  // Skip execution if GlobalSight status hasn't changed
  if ($status['status'] == $gs->code2status($record['status'])) {
    return false;
  }

  // So we have translations now!
  if ($status['status'] == 'EXPORTED' || $status['status'] == 'LOCALIZED') {
    // Get remote language mappings ('en' => 'en_US')
    $map = $translator->settings['remote_languages_mappings'];


    // Send API request to GS
    $translation = $gs->receive($record['job_name']);

    // Run link localization (if enabled)
    if (variable_get('tmgmt_globalsight_localize_links', 0) == 1) {
      foreach ($translation as $gs_lang => $values) {
        $targetLanguage = array_search($gs_lang, $map);
        foreach ($values as $field => $value) {
          foreach ($value as $key => $string) {
            $translation[$gs_lang][$field][$key] = tmgmt_globalsight_update_links($job->source_language, $targetLanguage, $string);
          }
        }
      }
    }

    // The translation "might" contain records for multiple jobs.
    if (isset($job->settings['associated_jobs'])) {
      foreach ($job->settings['associated_jobs'] as $associated_tjid => $associated_lang) {
        $gs_lang = $map[$associated_lang];
        if (isset($translation[$gs_lang])) {
          $associated_job = tmgmt_job_load($associated_tjid);
          $associated_job->setState(TMGMT_JOB_STATE_ACTIVE);


          // We sent tjiids of original job as keys to Globalsight. Now we need to convert these (wrong) tjiids into
          // ones belonging to appropriate parent job.

          // First we are loading good tjiids
          $items = $associated_job->getItems();
          $tjiids = array_keys($items);

          // Next we are remapping wrong tjiids we got from GlobalSight to proper ones
          $i = 0;
          $translated_data = array();
          foreach (tmgmt_unflatten_data($translation[$gs_lang]) as $wrong_tjiid => $data) {
            $translated_data[$tjiids[$i]] = $data;
            $i++;
          };

          //dsm($translated_data); return;

          $associated_job->addTranslatedData($translated_data);
//          $associated_job->finished();
//          $associated_job->save();

          $job->addMessage(t('Translation to @language finished.', array('@language' => $associated_lang)));

        } else {
          // We still do not have translation!
        }
      }
    }

    // Update translations per each job item
    $job->addTranslatedData(tmgmt_unflatten_data($translation[$map[$job->target_language]]));

    // Update our little mapping table -- archive job
    $record['status'] = 0;
    drupal_write_record('tmgmt_globalsight', $record, array('tjid'));
    return true;
  }
}

/**
 * Implements hook_tmgmt_translator_plugin_info().
 */
function tmgmt_globalsight_tmgmt_translator_plugin_info() {
  return array(
    'gs' => array(
      'label' => t('GlobalSight translator'),
      'description' => t('An open source translation management service.'),
      'plugin controller class' => 'TMGMTGlobalSightTranslatorPluginController',
      'ui controller class' => 'TMGMTGlobalSightTranslatorUIController',
      'default settings' => array(
        'endpoint' => '',
        'username' => '',
        'password' => '',
      ),
    ),
  );
}

function _tmgmt_globalsight_delete_job($tjid) {
  // Delete previous jobs (if any).
  $num_deleted = db_delete('tmgmt_globalsight')
    ->condition('tjid', $tjid)
    ->execute();

  return $num_deleted;
}

function _tmgmt_globalsight_archive_job($tjid) {
  $num_updated = db_update('tmgmt_globalsight')
    ->fields(array('status' => 0))
    ->condition('tjid', $tjid)
    ->execute();

  return $num_updated;
}
